# This Dockerfile builds the API only.

FROM python:latest
WORKDIR /app

COPY api/requirements.txt api/api.py api/.flaskenv ./
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5001
CMD ["gunicorn", "-b", ":5001", "api:app"]
